# Generated by Django 6.0.2 on 2026-03-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="interviewer_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="interview",
            name="candidate_name",
            field=models.CharField(default="V. Murphy", max_length=255),
        ),
    ]
