# Generated by Django 6.0.2 on 2026-03-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_interview_interviewer_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="industry",
        ),
        migrations.AddField(
            model_name="job",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SR", "Senior"),
                    ("ST", "Staff"),
                    ("PR", "Principal"),
                    ("LD", "Lead"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="candidate_name",
            field=models.CharField(default="Vinny Murphy", max_length=255),
        ),
    ]
