# Generated by Django 6.0.2 on 2026-03-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_remove_job_industry_job_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
