# Generated by Django 6.0.2 on 2026-03-04 20:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_job_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="requirements",
        ),
    ]
