# Generated by Django 6.0.2 on 2026-03-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_remove_job_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="interview_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="interview",
            name="interviewer_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
