# Generated by Django 6.0.2 on 2026-03-05 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_interview_interview_phone_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="interview",
            old_name="interview_phone",
            new_name="interviewer_phone",
        ),
        migrations.CreateModel(
            name="Interviewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interviewers",
                        to="jobs.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="interview",
            name="interviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="jobs.interviewer",
            ),
        ),
    ]
