# Generated by Django 6.0.2 on 2026-03-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_rename_interview_phone_interview_interviewer_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interview",
            name="interviewer_email",
        ),
        migrations.RemoveField(
            model_name="interview",
            name="interviewer_name",
        ),
        migrations.RemoveField(
            model_name="interview",
            name="interviewer_phone",
        ),
    ]
