# Generated by Django 6.0.2 on 2026-03-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0008_remove_interview_interviewer_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="is_remote",
        ),
        migrations.AddField(
            model_name="job",
            name="work_mode",
            field=models.CharField(
                choices=[
                    ("remote", "Remote"),
                    ("onsite", "On-site"),
                    ("hybrid", "Hybrid"),
                ],
                default="onsite",
                max_length=10,
            ),
        ),
    ]
