# Generated by Django 6.0.2 on 2026-03-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_remove_job_is_remote_job_work_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="application_link",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
