# Generated by Django 6.0.3 on 2026-03-22 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0010_alter_job_application_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="applied_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
