# Generated by Django 6.0.3 on 2026-03-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_job_applied_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("open", "Open"),
                    ("applied", "Applied"),
                    ("interviewing", "Interviewing"),
                    ("rejected", "Rejected"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=12,
            ),
        ),
    ]
