# Generated by Django 6.0.3 on 2026-04-30 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0013_alter_job_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interview",
            options={"ordering": ["-scheduled_time"]},
        ),
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-applied_date"]},
        ),
        migrations.AlterField(
            model_name="job",
            name="applied_date",
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("open", "Open"),
                    ("applied", "Applied"),
                    ("negotiating", "Negotiating"),
                    ("interviewing", "Interviewing"),
                    ("rejected", "Rejected"),
                    ("closed", "Closed"),
                ],
                db_index=True,
                default="open",
                max_length=12,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="interviewer",
            unique_together={("name", "company")},
        ),
    ]
