# Generated by Django 6.0.4 on 2026-05-04 19:16

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0014_alter_interview_options_alter_job_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="last_matched_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of the last semantic match", null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="match_score",
            field=models.JSONField(
                blank=True,
                help_text="Semantic match score (0-100) generated by LLM",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="slug",
            field=models.SlugField(
                blank=True, unique=True, validators=[jobs.models.validate_not_reserved]
            ),
        ),
    ]
