# Generated by Django 6.0.5 on 2026-05-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0015_job_last_matched_at_job_match_score_alter_job_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="meeting_link",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
