# Generated by Django 6.0.5 on 2026-06-25 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0016_interview_meeting_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the resume (e.g., 'Software Engineer Resume')",
                        max_length=100,
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(
                        help_text="The extracted plain text used for LLM context processing."
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Optional original PDF storage.",
                        null=True,
                        upload_to="resumes/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates if this is the primary resume for default match comparisons.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the resume was created.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Resumes",
                "ordering": ["-updated_at"],
            },
        ),
    ]
