repos:
-   repo: local
    hooks:
    -   id: django-tests
        name: django-tests
        entry: python manage.py test
        language: system
        pass_filenames: false
        always_run: true
